# Generated by Django 4.0 on 2022-02-27 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescGram',
            fields=[
                ('GramKey', models.CharField(default='NA', max_length=30, primary_key=True, serialize=False)),
                ('GramIndicator', models.CharField(default='NA', max_length=20)),
                ('Text', models.TextField()),
                ('Category', models.CharField(default='', max_length=200)),
                ('TopicNum', models.IntegerField(default=0)),
                ('Embedding1', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('Embedding2', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('Embedding3', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('JobCode', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(default='N/A', max_length=400)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GramRelated', models.CharField(max_length=40)),
                ('GramPrimary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateddesc_encrypt', to='jobdescriptions.descgram')),
            ],
        ),
        migrations.AddField(
            model_name='descgram',
            name='JobCodeKey',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='desc_encrypt', to='jobdescriptions.jobtitles'),
        ),
    ]
