# Generated by Django 4.0 on 2022-02-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('Key', models.CharField(default='N/A', max_length=100, primary_key=True, serialize=False)),
                ('ModelName', models.CharField(choices=[('EmployeeState', 'EmployeeState'), ('Department', 'Department'), ('JobTable', 'JobTable')], default='', max_length=40)),
                ('AttrName', models.CharField(default='', max_length=100)),
                ('IsKeyField', models.BooleanField(default=False)),
                ('FieldName', models.CharField(default='', max_length=100)),
                ('HeaderName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
