# Generated by Django 4.0 on 2022-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='DataType',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Freeform', 'Freeform')], default='Text', max_length=100),
        ),
    ]
