# Generated by Django 4.0 on 2022-02-27 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptID', models.CharField(default='N/A', max_length=400, primary_key=True, serialize=False)),
                ('LastChangeDate', models.DateField(verbose_name='Date')),
            ],
            managers=[
                ('Object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDates',
            fields=[
                ('EmpDateKey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CurrDate', models.DateField(verbose_name='Date')),
                ('PrevDate', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Date')),
                ('NextDate', models.DateField(default=datetime.datetime(3300, 1, 1, 0, 0), verbose_name='Date')),
                ('Status', models.CharField(choices=[('hire', 'HIRE'), ('term', 'TERMINATION'), ('entry', 'Entry'), ('promo', 'PROMOTION')], default='entry', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.CharField(default='N/A', max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='N/A', max_length=200)),
                ('CreateDate', models.DateField(verbose_name='Date')),
                ('EmailAddress', models.CharField(default='N/A', max_length=100)),
            ],
            managers=[
                ('Object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('ModelName', models.CharField(default='Default', max_length=100, primary_key=True, serialize=False)),
                ('CreateDate', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('ModelName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CreateDate', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('RuleKey', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Operation', models.CharField(choices=[('and', 'and'), ('or', 'or')], default='and', max_length=50)),
                ('Field1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enc_rulefield1', to='fields.fieldmapping')),
                ('Field2', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, related_name='enc_rulefield2', to='fields.fieldmapping')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enc_ruleset', to='employee.rulemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExceptionVal', models.CharField(max_length=300)),
                ('FieldNo', models.IntegerField(default=0)),
                ('Rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enc_exception', to='employee.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='N/A', max_length=200)),
                ('Status', models.CharField(choices=[('hire', 'HIRE'), ('term', 'TERMINATION'), ('entry', 'Entry'), ('promo', 'PROMOTION')], default='entry', max_length=50)),
                ('Date', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Date')),
                ('JobCode', models.CharField(default='N/A', max_length=120)),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Location', models.CharField(default='N/A', max_length=120)),
                ('ServiceLine', models.CharField(default='N/A', max_length=120)),
                ('Embedding1', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Embedding2', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('DeptID', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.PROTECT, related_name='emp_dept', to='employee.department')),
                ('EmpDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enc_date_state', to='employee.empdates')),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptEmp', to='employee.employee')),
                ('ModelKey', models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='emp_model', to='employee.empmodel')),
                ('ReportsToID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enc_reports', to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='empdates',
            name='EmpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptEmpDate', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='empdates',
            name='ModelKey',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='empdate_model', to='employee.empmodel'),
        ),
        migrations.CreateModel(
            name='DepartmentAttrs',
            fields=[
                ('AttrKey', models.CharField(default='N/A', max_length=100, primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(default='N/A', max_length=200)),
                ('AsofDate', models.DateField(verbose_name='Date')),
                ('NextDate', models.DateField(default=datetime.datetime(3300, 1, 1, 0, 0), verbose_name='Date')),
                ('IsMostRecent', models.BooleanField()),
                ('Attribute1', models.CharField(default='N/A', max_length=400)),
                ('Attribute2', models.CharField(default='N/A', max_length=400)),
                ('Attribute3', models.CharField(default='N/A', max_length=400)),
                ('Attribute4', models.CharField(default='N/A', max_length=400)),
                ('Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enc_deptdate', to='employee.department')),
            ],
            managers=[
                ('Object', django.db.models.manager.Manager()),
            ],
        ),
    ]
