# Generated by Django 4.0 on 2022-03-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_state',
            name='DeptID',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='emp_dept', to='employee.department'),
        ),
    ]
