# Generated by Django 4.0 on 2022-02-27 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('ModelName', models.CharField(default='N/A', max_length=400, primary_key=True, serialize=False)),
                ('ChartType', models.CharField(choices=[('Table', 'Table'), ('Bar', 'Bar'), ('Line', 'Line'), ('Bubble', 'Bubble')], default='Table', max_length=50)),
                ('Status', models.CharField(choices=[('Hire', 'Hire'), ('Term', 'Term'), ('entry', 'Entry'), ('Promo', 'Promo')], default='entry', max_length=50)),
                ('XFieldName', models.CharField(default='N/A', max_length=400)),
                ('YFieldName', models.CharField(default='N/A', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='BasicQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variable', models.CharField(default='N/A', max_length=400)),
                ('Value', models.CharField(default='N/A', max_length=400)),
                ('ModelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enc_basic', to='query.querymodel')),
            ],
        ),
    ]
