# Generated by Django 4.0 on 2022-03-05 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicquery',
            name='DateVar',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Date'),
        ),
    ]
