# Generated by Django 4.0 on 2022-03-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_basicquery_datevar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymodel',
            name='YFieldName',
        ),
    ]
