# Generated by Django 4.0 on 2022-03-06 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_empdates_status_alter_employee_state_status'),
        ('query', '0003_remove_querymodel_yfieldname'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='AsofDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 6, 12, 18, 51, 967731), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='querymodel',
            name='NPeriods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='querymodel',
            name='Period',
            field=models.CharField(choices=[('None', 'None'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='querymodel',
            name='RuleModelName',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='enc_qryrule', to='employee.rulemodel'),
            preserve_default=False,
        ),
    ]
