# Generated by Django 4.0 on 2022-03-06 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_empdates_status_alter_employee_state_status'),
        ('query', '0004_querymodel_asofdate_querymodel_nperiods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='AsofDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 6, 13, 25, 0, 18746), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='RuleModelName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enc_qryrule', to='employee.rulemodel'),
        ),
    ]
