# Generated by Django 4.0 on 2022-03-07 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_alter_querymodel_asofdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='AsofDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 7, 11, 35, 42, 656203), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='Status',
            field=models.CharField(choices=[('Hire', 'Hire'), ('Term', 'Term'), ('demographic', 'Demographic'), ('Promo', 'Promo')], default='entry', max_length=50),
        ),
    ]
