# Generated by Django 4.0 on 2022-03-14 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_alter_querymodel_asofdate_alter_querymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='FieldBand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='AsofDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 18, 58, 44, 790836), verbose_name='Date'),
        ),
    ]
