# Generated by Django 4.0 on 2022-03-17 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_querymodel_fieldband_alter_querymodel_asofdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='AsofDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 17, 15, 30, 2, 316724), verbose_name='Date'),
        ),
    ]
