# Generated by Django 4.0 on 2022-03-17 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_alter_querymodel_asofdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='AsofDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 17, 15, 48, 5, 860487), verbose_name='Date'),
        ),
    ]
